### ISSUE TITLE
display 4 surveys to users

### ISSUE THREAD

**Issue by lonnen** [mozilla/pioneer-study-online-news#12]
users should be prompted with a survey:
- [ ] at enrollment
- [ ] before the intervention starts
- [ ] after the intervention ends
- [ ] in the final week of the study

@rjweiss to provide links to each survey

**Comment by mythmon** [comment]
How do we want to display the survey to users? Options I'm aware of are:

1) Pop-over
2) Pop-under
3) Heartbeat-style notification bar
4) Doorhanger-style notification bar
5) Toolbar icon with a notification bubble

Some of these can be combined, such as the toolbar icon and doorhanger, or a heartbeat and a popunder.

**Comment by lonnen** [comment]
I believe 3 or 4. I think 3 has the best prior art.

**Comment by mythmon** [comment]
I think we'll already be using door hangers (4) for other purposes in the study, so it may make sense to simply re-use that instead of building two UIs.

**Comment by mythmon** [comment]
These surveys mark the boundaries between different phases of the study. Should each phase wait until the user interacts with the survey? If the user does not interact with the survey prompt, should they be prompted again at some point?

**Comment by mythmon** [comment]
<img width="391" alt="mobile-doorhanger" src="https://user-images.githubusercontent.com/305049/31744290-18dc0b54-b413-11e7-99b7-09d04edc87d8.png">

Here  is a doorhanger prompt from another study, provided by @raymak. I think that for us we'd want a short blurb explaining the study and/or the survey the user is about to open.

* The blue button would open the survey (and mark the user as engaged, in order to allow them to move to the next phase).
* The grey button would dismiss the notification temporarily.
* The checkbox would be labeled something like "I do not want to participate in this study", and if checked would end the study. Maybe we leave this out, or only show it on the first prompt, since users can also opt-out via about:studies.

We would need an icon, and copy for the doorhanger.

How does this look, @lonnen @rjweiss?

**Comment by mythmon** [comment]
@raymak tells me that we are learning from CFR that door hangers tend to outperform heartbeat-style notifications.

**Comment by rjweiss** [comment]
1. "Take survey" and "Not now" seem fine to me.
2. I agree with no checkbox, about:studies for opt-out.
3. @mythmon is there way to keep track of how many times someone has dismissed the survey prompt?  For example, prompt them 3 times but if they dismiss it 3 times, we don't prompt them again?  I think it is more important to strictly follow the schedule (3 weeks pre-treatment observation, 3 weeks doorhanger notifications about alignment scoring, 3 weeks post-treatment observation) than ensure that people have filled out the surveys,

**Comment by rjweiss** [comment]
@mythmon Can I provide the surveys as four separate surveygizmo links?  And will the normandy include the normandy id for each survey if so?

(I want to make sure that if we provide four separate surveygizmo links, we will be able to correspond responses to each survey across the study using the normandy id).

**Comment by mythmon** [comment]
Ok, so the survey will prompt up to 3 times until the user interacts with it, but it won't block progress of the study.

Four separate surveygizmo links would be preferred, yes. We'll pass along the pioneer id of users in a query parameter to the survey. This is also included in all the telemetry pings. The exact nature of the pioneer ID is still undecided, but it will at least be unique per user and the same for the entire study.

**Comment by rjweiss** [comment]
Perfect.  I'll prepare four separate SG urls.

**Comment by lonnen** [comment]
leave out the checkbox. otherwise that looks fine.

**Comment by rjweiss** [comment]
Survey Wave 1: https://qsurvey.mozilla.com/s3/Pioneer-Online-News-Wave-1
Survey Wave 2: https://qsurvey.mozilla.com/s3/Pioneer-Online-News-Wave-2
Survey Wave 3: https://qsurvey.mozilla.com/s3/Pioneer-Online-News-Wave-3
Survey Wave 4: https://qsurvey.mozilla.com/s3/Pioneer-Online-News-Wave-4

These are all blank surveys for now, but the URL will not change.
